// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package passkey

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// newRedisClientMock creates a new instance of redisClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRedisClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *redisClientMock {
	mock := &redisClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// redisClientMock is an autogenerated mock type for the redisClient type
type redisClientMock struct {
	mock.Mock
}

type redisClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *redisClientMock) EXPECT() *redisClientMock_Expecter {
	return &redisClientMock_Expecter{mock: &_m.Mock}
}

// Del provides a mock function for the type redisClientMock
func (_mock *redisClientMock) Del(ctx context.Context, keys ...string) *redis.IntCmd {
	// string
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 *redis.IntCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) *redis.IntCmd); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.IntCmd)
		}
	}
	return r0
}

// redisClientMock_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type redisClientMock_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *redisClientMock_Expecter) Del(ctx interface{}, keys ...interface{}) *redisClientMock_Del_Call {
	return &redisClientMock_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *redisClientMock_Del_Call) Run(run func(ctx context.Context, keys ...string)) *redisClientMock_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *redisClientMock_Del_Call) Return(intCmd *redis.IntCmd) *redisClientMock_Del_Call {
	_c.Call.Return(intCmd)
	return _c
}

func (_c *redisClientMock_Del_Call) RunAndReturn(run func(ctx context.Context, keys ...string) *redis.IntCmd) *redisClientMock_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type redisClientMock
func (_mock *redisClientMock) Get(ctx context.Context, key string) *redis.StringCmd {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *redis.StringCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *redis.StringCmd); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StringCmd)
		}
	}
	return r0
}

// redisClientMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type redisClientMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *redisClientMock_Expecter) Get(ctx interface{}, key interface{}) *redisClientMock_Get_Call {
	return &redisClientMock_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *redisClientMock_Get_Call) Run(run func(ctx context.Context, key string)) *redisClientMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *redisClientMock_Get_Call) Return(stringCmd *redis.StringCmd) *redisClientMock_Get_Call {
	_c.Call.Return(stringCmd)
	return _c
}

func (_c *redisClientMock_Get_Call) RunAndReturn(run func(ctx context.Context, key string) *redis.StringCmd) *redisClientMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type redisClientMock
func (_mock *redisClientMock) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) *redis.StatusCmd {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *redis.StatusCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) *redis.StatusCmd); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}
	return r0
}

// redisClientMock_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type redisClientMock_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *redisClientMock_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *redisClientMock_Set_Call {
	return &redisClientMock_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *redisClientMock_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *redisClientMock_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *redisClientMock_Set_Call) Return(statusCmd *redis.StatusCmd) *redisClientMock_Set_Call {
	_c.Call.Return(statusCmd)
	return _c
}

func (_c *redisClientMock_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value interface{}, expiration time.Duration) *redis.StatusCmd) *redisClientMock_Set_Call {
	_c.Call.Return(run)
	return _c
}
