// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package passkey

import (
	mock "github.com/stretchr/testify/mock"
)

// newSessionStoreInterfaceMock creates a new instance of sessionStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSessionStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *sessionStoreInterfaceMock {
	mock := &sessionStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// sessionStoreInterfaceMock is an autogenerated mock type for the sessionStoreInterface type
type sessionStoreInterfaceMock struct {
	mock.Mock
}

type sessionStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *sessionStoreInterfaceMock) EXPECT() *sessionStoreInterfaceMock_Expecter {
	return &sessionStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// deleteSession provides a mock function for the type sessionStoreInterfaceMock
func (_mock *sessionStoreInterfaceMock) deleteSession(sessionKey string) error {
	ret := _mock.Called(sessionKey)

	if len(ret) == 0 {
		panic("no return value specified for deleteSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(sessionKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// sessionStoreInterfaceMock_deleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'deleteSession'
type sessionStoreInterfaceMock_deleteSession_Call struct {
	*mock.Call
}

// deleteSession is a helper method to define mock.On call
//   - sessionKey string
func (_e *sessionStoreInterfaceMock_Expecter) deleteSession(sessionKey interface{}) *sessionStoreInterfaceMock_deleteSession_Call {
	return &sessionStoreInterfaceMock_deleteSession_Call{Call: _e.mock.On("deleteSession", sessionKey)}
}

func (_c *sessionStoreInterfaceMock_deleteSession_Call) Run(run func(sessionKey string)) *sessionStoreInterfaceMock_deleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *sessionStoreInterfaceMock_deleteSession_Call) Return(err error) *sessionStoreInterfaceMock_deleteSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *sessionStoreInterfaceMock_deleteSession_Call) RunAndReturn(run func(sessionKey string) error) *sessionStoreInterfaceMock_deleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// retrieveSession provides a mock function for the type sessionStoreInterfaceMock
func (_mock *sessionStoreInterfaceMock) retrieveSession(sessionKey string) (*sessionData, error) {
	ret := _mock.Called(sessionKey)

	if len(ret) == 0 {
		panic("no return value specified for retrieveSession")
	}

	var r0 *sessionData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*sessionData, error)); ok {
		return returnFunc(sessionKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *sessionData); ok {
		r0 = returnFunc(sessionKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessionData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(sessionKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// sessionStoreInterfaceMock_retrieveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'retrieveSession'
type sessionStoreInterfaceMock_retrieveSession_Call struct {
	*mock.Call
}

// retrieveSession is a helper method to define mock.On call
//   - sessionKey string
func (_e *sessionStoreInterfaceMock_Expecter) retrieveSession(sessionKey interface{}) *sessionStoreInterfaceMock_retrieveSession_Call {
	return &sessionStoreInterfaceMock_retrieveSession_Call{Call: _e.mock.On("retrieveSession", sessionKey)}
}

func (_c *sessionStoreInterfaceMock_retrieveSession_Call) Run(run func(sessionKey string)) *sessionStoreInterfaceMock_retrieveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *sessionStoreInterfaceMock_retrieveSession_Call) Return(v *sessionData, err error) *sessionStoreInterfaceMock_retrieveSession_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *sessionStoreInterfaceMock_retrieveSession_Call) RunAndReturn(run func(sessionKey string) (*sessionData, error)) *sessionStoreInterfaceMock_retrieveSession_Call {
	_c.Call.Return(run)
	return _c
}

// storeSession provides a mock function for the type sessionStoreInterfaceMock
func (_mock *sessionStoreInterfaceMock) storeSession(sessionKey string, session *sessionData, expirySeconds int64) error {
	ret := _mock.Called(sessionKey, session, expirySeconds)

	if len(ret) == 0 {
		panic("no return value specified for storeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *sessionData, int64) error); ok {
		r0 = returnFunc(sessionKey, session, expirySeconds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// sessionStoreInterfaceMock_storeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'storeSession'
type sessionStoreInterfaceMock_storeSession_Call struct {
	*mock.Call
}

// storeSession is a helper method to define mock.On call
//   - sessionKey string
//   - session *sessionData
//   - expirySeconds int64
func (_e *sessionStoreInterfaceMock_Expecter) storeSession(sessionKey interface{}, session interface{}, expirySeconds interface{}) *sessionStoreInterfaceMock_storeSession_Call {
	return &sessionStoreInterfaceMock_storeSession_Call{Call: _e.mock.On("storeSession", sessionKey, session, expirySeconds)}
}

func (_c *sessionStoreInterfaceMock_storeSession_Call) Run(run func(sessionKey string, session *sessionData, expirySeconds int64)) *sessionStoreInterfaceMock_storeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *sessionData
		if args[1] != nil {
			arg1 = args[1].(*sessionData)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *sessionStoreInterfaceMock_storeSession_Call) Return(err error) *sessionStoreInterfaceMock_storeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *sessionStoreInterfaceMock_storeSession_Call) RunAndReturn(run func(sessionKey string, session *sessionData, expirySeconds int64) error) *sessionStoreInterfaceMock_storeSession_Call {
	_c.Call.Return(run)
	return _c
}
