// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package application

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/internal/application/model"
	"github.com/thunder-id/thunderid/internal/entity"
	"github.com/thunder-id/thunderid/internal/resource"
	"github.com/thunder-id/thunderid/internal/system/resourcedependency"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/providers"
)

// NewApplicationServiceInterfaceMock creates a new instance of ApplicationServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApplicationServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ApplicationServiceInterfaceMock {
	mock := &ApplicationServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ApplicationServiceInterfaceMock is an autogenerated mock type for the ApplicationServiceInterface type
type ApplicationServiceInterfaceMock struct {
	mock.Mock
}

type ApplicationServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ApplicationServiceInterfaceMock) EXPECT() *ApplicationServiceInterfaceMock_Expecter {
	return &ApplicationServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateApplication provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) CreateApplication(ctx context.Context, app *model.ApplicationDTO) (*model.ApplicationDTO, *common.ServiceError) {
	ret := _mock.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for CreateApplication")
	}

	var r0 *model.ApplicationDTO
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ApplicationDTO) (*model.ApplicationDTO, *common.ServiceError)); ok {
		return returnFunc(ctx, app)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ApplicationDTO) *model.ApplicationDTO); ok {
		r0 = returnFunc(ctx, app)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApplicationDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ApplicationDTO) *common.ServiceError); ok {
		r1 = returnFunc(ctx, app)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_CreateApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApplication'
type ApplicationServiceInterfaceMock_CreateApplication_Call struct {
	*mock.Call
}

// CreateApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - app *model.ApplicationDTO
func (_e *ApplicationServiceInterfaceMock_Expecter) CreateApplication(ctx interface{}, app interface{}) *ApplicationServiceInterfaceMock_CreateApplication_Call {
	return &ApplicationServiceInterfaceMock_CreateApplication_Call{Call: _e.mock.On("CreateApplication", ctx, app)}
}

func (_c *ApplicationServiceInterfaceMock_CreateApplication_Call) Run(run func(ctx context.Context, app *model.ApplicationDTO)) *ApplicationServiceInterfaceMock_CreateApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ApplicationDTO
		if args[1] != nil {
			arg1 = args[1].(*model.ApplicationDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_CreateApplication_Call) Return(applicationDTO *model.ApplicationDTO, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_CreateApplication_Call {
	_c.Call.Return(applicationDTO, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_CreateApplication_Call) RunAndReturn(run func(ctx context.Context, app *model.ApplicationDTO) (*model.ApplicationDTO, *common.ServiceError)) *ApplicationServiceInterfaceMock_CreateApplication_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApplication provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) DeleteApplication(ctx context.Context, appID string) *common.ServiceError {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApplication")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ApplicationServiceInterfaceMock_DeleteApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApplication'
type ApplicationServiceInterfaceMock_DeleteApplication_Call struct {
	*mock.Call
}

// DeleteApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *ApplicationServiceInterfaceMock_Expecter) DeleteApplication(ctx interface{}, appID interface{}) *ApplicationServiceInterfaceMock_DeleteApplication_Call {
	return &ApplicationServiceInterfaceMock_DeleteApplication_Call{Call: _e.mock.On("DeleteApplication", ctx, appID)}
}

func (_c *ApplicationServiceInterfaceMock_DeleteApplication_Call) Run(run func(ctx context.Context, appID string)) *ApplicationServiceInterfaceMock_DeleteApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_DeleteApplication_Call) Return(serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_DeleteApplication_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_DeleteApplication_Call) RunAndReturn(run func(ctx context.Context, appID string) *common.ServiceError) *ApplicationServiceInterfaceMock_DeleteApplication_Call {
	_c.Call.Return(run)
	return _c
}

// DisableApplicationInboundAccess provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) DisableApplicationInboundAccess(ctx context.Context, appID string) *common.ServiceError {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for DisableApplicationInboundAccess")
	}

	var r0 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *common.ServiceError); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.ServiceError)
		}
	}
	return r0
}

// ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableApplicationInboundAccess'
type ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call struct {
	*mock.Call
}

// DisableApplicationInboundAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *ApplicationServiceInterfaceMock_Expecter) DisableApplicationInboundAccess(ctx interface{}, appID interface{}) *ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call {
	return &ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call{Call: _e.mock.On("DisableApplicationInboundAccess", ctx, appID)}
}

func (_c *ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call) Run(run func(ctx context.Context, appID string)) *ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call) Return(serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call) RunAndReturn(run func(ctx context.Context, appID string) *common.ServiceError) *ApplicationServiceInterfaceMock_DisableApplicationInboundAccess_Call {
	_c.Call.Return(run)
	return _c
}

// EnableApplicationInboundAccess provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) EnableApplicationInboundAccess(ctx context.Context, appID string, identifier string) (*model.ApplicationInboundAccessResponse, *common.ServiceError) {
	ret := _mock.Called(ctx, appID, identifier)

	if len(ret) == 0 {
		panic("no return value specified for EnableApplicationInboundAccess")
	}

	var r0 *model.ApplicationInboundAccessResponse
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.ApplicationInboundAccessResponse, *common.ServiceError)); ok {
		return returnFunc(ctx, appID, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.ApplicationInboundAccessResponse); ok {
		r0 = returnFunc(ctx, appID, identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApplicationInboundAccessResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, appID, identifier)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableApplicationInboundAccess'
type ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call struct {
	*mock.Call
}

// EnableApplicationInboundAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - identifier string
func (_e *ApplicationServiceInterfaceMock_Expecter) EnableApplicationInboundAccess(ctx interface{}, appID interface{}, identifier interface{}) *ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call {
	return &ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call{Call: _e.mock.On("EnableApplicationInboundAccess", ctx, appID, identifier)}
}

func (_c *ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call) Run(run func(ctx context.Context, appID string, identifier string)) *ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call) Return(applicationInboundAccessResponse *model.ApplicationInboundAccessResponse, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call {
	_c.Call.Return(applicationInboundAccessResponse, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call) RunAndReturn(run func(ctx context.Context, appID string, identifier string) (*model.ApplicationInboundAccessResponse, *common.ServiceError)) *ApplicationServiceInterfaceMock_EnableApplicationInboundAccess_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplication provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) GetApplication(ctx context.Context, appID string) (*providers.Application, *common.ServiceError) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetApplication")
	}

	var r0 *providers.Application
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*providers.Application, *common.ServiceError)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *providers.Application); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Application)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_GetApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplication'
type ApplicationServiceInterfaceMock_GetApplication_Call struct {
	*mock.Call
}

// GetApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *ApplicationServiceInterfaceMock_Expecter) GetApplication(ctx interface{}, appID interface{}) *ApplicationServiceInterfaceMock_GetApplication_Call {
	return &ApplicationServiceInterfaceMock_GetApplication_Call{Call: _e.mock.On("GetApplication", ctx, appID)}
}

func (_c *ApplicationServiceInterfaceMock_GetApplication_Call) Run(run func(ctx context.Context, appID string)) *ApplicationServiceInterfaceMock_GetApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetApplication_Call) Return(application *providers.Application, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_GetApplication_Call {
	_c.Call.Return(application, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetApplication_Call) RunAndReturn(run func(ctx context.Context, appID string) (*providers.Application, *common.ServiceError)) *ApplicationServiceInterfaceMock_GetApplication_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplicationDeclarativeInboundAccess provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) GetApplicationDeclarativeInboundAccess(ctx context.Context, appID string) (*providers.DeclarativeInboundAccess, *common.ServiceError) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationDeclarativeInboundAccess")
	}

	var r0 *providers.DeclarativeInboundAccess
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*providers.DeclarativeInboundAccess, *common.ServiceError)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *providers.DeclarativeInboundAccess); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.DeclarativeInboundAccess)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplicationDeclarativeInboundAccess'
type ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call struct {
	*mock.Call
}

// GetApplicationDeclarativeInboundAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *ApplicationServiceInterfaceMock_Expecter) GetApplicationDeclarativeInboundAccess(ctx interface{}, appID interface{}) *ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call {
	return &ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call{Call: _e.mock.On("GetApplicationDeclarativeInboundAccess", ctx, appID)}
}

func (_c *ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call) Run(run func(ctx context.Context, appID string)) *ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call) Return(declarativeInboundAccess *providers.DeclarativeInboundAccess, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call {
	_c.Call.Return(declarativeInboundAccess, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call) RunAndReturn(run func(ctx context.Context, appID string) (*providers.DeclarativeInboundAccess, *common.ServiceError)) *ApplicationServiceInterfaceMock_GetApplicationDeclarativeInboundAccess_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplicationInboundAccess provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) GetApplicationInboundAccess(ctx context.Context, appID string) (*model.ApplicationInboundAccessResponse, *common.ServiceError) {
	ret := _mock.Called(ctx, appID)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationInboundAccess")
	}

	var r0 *model.ApplicationInboundAccessResponse
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ApplicationInboundAccessResponse, *common.ServiceError)); ok {
		return returnFunc(ctx, appID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ApplicationInboundAccessResponse); ok {
		r0 = returnFunc(ctx, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApplicationInboundAccessResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, appID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplicationInboundAccess'
type ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call struct {
	*mock.Call
}

// GetApplicationInboundAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
func (_e *ApplicationServiceInterfaceMock_Expecter) GetApplicationInboundAccess(ctx interface{}, appID interface{}) *ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call {
	return &ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call{Call: _e.mock.On("GetApplicationInboundAccess", ctx, appID)}
}

func (_c *ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call) Run(run func(ctx context.Context, appID string)) *ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call) Return(applicationInboundAccessResponse *model.ApplicationInboundAccessResponse, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call {
	_c.Call.Return(applicationInboundAccessResponse, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call) RunAndReturn(run func(ctx context.Context, appID string) (*model.ApplicationInboundAccessResponse, *common.ServiceError)) *ApplicationServiceInterfaceMock_GetApplicationInboundAccess_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplicationList provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) GetApplicationList(ctx context.Context) (*model.ApplicationListResponse, *common.ServiceError) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationList")
	}

	var r0 *model.ApplicationListResponse
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.ApplicationListResponse, *common.ServiceError)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.ApplicationListResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApplicationListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) *common.ServiceError); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_GetApplicationList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplicationList'
type ApplicationServiceInterfaceMock_GetApplicationList_Call struct {
	*mock.Call
}

// GetApplicationList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ApplicationServiceInterfaceMock_Expecter) GetApplicationList(ctx interface{}) *ApplicationServiceInterfaceMock_GetApplicationList_Call {
	return &ApplicationServiceInterfaceMock_GetApplicationList_Call{Call: _e.mock.On("GetApplicationList", ctx)}
}

func (_c *ApplicationServiceInterfaceMock_GetApplicationList_Call) Run(run func(ctx context.Context)) *ApplicationServiceInterfaceMock_GetApplicationList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetApplicationList_Call) Return(applicationListResponse *model.ApplicationListResponse, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_GetApplicationList_Call {
	_c.Call.Return(applicationListResponse, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetApplicationList_Call) RunAndReturn(run func(ctx context.Context) (*model.ApplicationListResponse, *common.ServiceError)) *ApplicationServiceInterfaceMock_GetApplicationList_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthApplication provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) GetOAuthApplication(ctx context.Context, clientID string) (*providers.OAuthClient, *common.ServiceError) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthApplication")
	}

	var r0 *providers.OAuthClient
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*providers.OAuthClient, *common.ServiceError)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *providers.OAuthClient); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.OAuthClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_GetOAuthApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthApplication'
type ApplicationServiceInterfaceMock_GetOAuthApplication_Call struct {
	*mock.Call
}

// GetOAuthApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *ApplicationServiceInterfaceMock_Expecter) GetOAuthApplication(ctx interface{}, clientID interface{}) *ApplicationServiceInterfaceMock_GetOAuthApplication_Call {
	return &ApplicationServiceInterfaceMock_GetOAuthApplication_Call{Call: _e.mock.On("GetOAuthApplication", ctx, clientID)}
}

func (_c *ApplicationServiceInterfaceMock_GetOAuthApplication_Call) Run(run func(ctx context.Context, clientID string)) *ApplicationServiceInterfaceMock_GetOAuthApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetOAuthApplication_Call) Return(oAuthClient *providers.OAuthClient, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_GetOAuthApplication_Call {
	_c.Call.Return(oAuthClient, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetOAuthApplication_Call) RunAndReturn(run func(ctx context.Context, clientID string) (*providers.OAuthClient, *common.ServiceError)) *ApplicationServiceInterfaceMock_GetOAuthApplication_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceDependencies provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) GetResourceDependencies(ctx context.Context, resourceType string, id string) ([]resourcedependency.ResourceDependency, error) {
	ret := _mock.Called(ctx, resourceType, id)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceDependencies")
	}

	var r0 []resourcedependency.ResourceDependency
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]resourcedependency.ResourceDependency, error)); ok {
		return returnFunc(ctx, resourceType, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []resourcedependency.ResourceDependency); ok {
		r0 = returnFunc(ctx, resourceType, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resourcedependency.ResourceDependency)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, resourceType, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_GetResourceDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceDependencies'
type ApplicationServiceInterfaceMock_GetResourceDependencies_Call struct {
	*mock.Call
}

// GetResourceDependencies is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceType string
//   - id string
func (_e *ApplicationServiceInterfaceMock_Expecter) GetResourceDependencies(ctx interface{}, resourceType interface{}, id interface{}) *ApplicationServiceInterfaceMock_GetResourceDependencies_Call {
	return &ApplicationServiceInterfaceMock_GetResourceDependencies_Call{Call: _e.mock.On("GetResourceDependencies", ctx, resourceType, id)}
}

func (_c *ApplicationServiceInterfaceMock_GetResourceDependencies_Call) Run(run func(ctx context.Context, resourceType string, id string)) *ApplicationServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetResourceDependencies_Call) Return(resourceDependencys []resourcedependency.ResourceDependency, err error) *ApplicationServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Return(resourceDependencys, err)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_GetResourceDependencies_Call) RunAndReturn(run func(ctx context.Context, resourceType string, id string) ([]resourcedependency.ResourceDependency, error)) *ApplicationServiceInterfaceMock_GetResourceDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// LoadDeclarativeInboundAccess provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) LoadDeclarativeInboundAccess(ctx context.Context, appID string, ouID string, name string, access *providers.DeclarativeInboundAccess) (string, error) {
	ret := _mock.Called(ctx, appID, ouID, name, access)

	if len(ret) == 0 {
		panic("no return value specified for LoadDeclarativeInboundAccess")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *providers.DeclarativeInboundAccess) (string, error)); ok {
		return returnFunc(ctx, appID, ouID, name, access)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *providers.DeclarativeInboundAccess) string); ok {
		r0 = returnFunc(ctx, appID, ouID, name, access)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *providers.DeclarativeInboundAccess) error); ok {
		r1 = returnFunc(ctx, appID, ouID, name, access)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadDeclarativeInboundAccess'
type ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call struct {
	*mock.Call
}

// LoadDeclarativeInboundAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - ouID string
//   - name string
//   - access *providers.DeclarativeInboundAccess
func (_e *ApplicationServiceInterfaceMock_Expecter) LoadDeclarativeInboundAccess(ctx interface{}, appID interface{}, ouID interface{}, name interface{}, access interface{}) *ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call {
	return &ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call{Call: _e.mock.On("LoadDeclarativeInboundAccess", ctx, appID, ouID, name, access)}
}

func (_c *ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call) Run(run func(ctx context.Context, appID string, ouID string, name string, access *providers.DeclarativeInboundAccess)) *ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *providers.DeclarativeInboundAccess
		if args[4] != nil {
			arg4 = args[4].(*providers.DeclarativeInboundAccess)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call) Return(s string, err error) *ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call) RunAndReturn(run func(ctx context.Context, appID string, ouID string, name string, access *providers.DeclarativeInboundAccess) (string, error)) *ApplicationServiceInterfaceMock_LoadDeclarativeInboundAccess_Call {
	_c.Call.Return(run)
	return _c
}

// SetDependencyRegistry provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) SetDependencyRegistry(r resourcedependency.Registry) {
	_mock.Called(r)
	return
}

// ApplicationServiceInterfaceMock_SetDependencyRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDependencyRegistry'
type ApplicationServiceInterfaceMock_SetDependencyRegistry_Call struct {
	*mock.Call
}

// SetDependencyRegistry is a helper method to define mock.On call
//   - r resourcedependency.Registry
func (_e *ApplicationServiceInterfaceMock_Expecter) SetDependencyRegistry(r interface{}) *ApplicationServiceInterfaceMock_SetDependencyRegistry_Call {
	return &ApplicationServiceInterfaceMock_SetDependencyRegistry_Call{Call: _e.mock.On("SetDependencyRegistry", r)}
}

func (_c *ApplicationServiceInterfaceMock_SetDependencyRegistry_Call) Run(run func(r resourcedependency.Registry)) *ApplicationServiceInterfaceMock_SetDependencyRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 resourcedependency.Registry
		if args[0] != nil {
			arg0 = args[0].(resourcedependency.Registry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_SetDependencyRegistry_Call) Return() *ApplicationServiceInterfaceMock_SetDependencyRegistry_Call {
	_c.Call.Return()
	return _c
}

func (_c *ApplicationServiceInterfaceMock_SetDependencyRegistry_Call) RunAndReturn(run func(r resourcedependency.Registry)) *ApplicationServiceInterfaceMock_SetDependencyRegistry_Call {
	_c.Run(run)
	return _c
}

// SetEntityService provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) SetEntityService(es entity.EntityServiceInterface) {
	_mock.Called(es)
	return
}

// ApplicationServiceInterfaceMock_SetEntityService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEntityService'
type ApplicationServiceInterfaceMock_SetEntityService_Call struct {
	*mock.Call
}

// SetEntityService is a helper method to define mock.On call
//   - es entity.EntityServiceInterface
func (_e *ApplicationServiceInterfaceMock_Expecter) SetEntityService(es interface{}) *ApplicationServiceInterfaceMock_SetEntityService_Call {
	return &ApplicationServiceInterfaceMock_SetEntityService_Call{Call: _e.mock.On("SetEntityService", es)}
}

func (_c *ApplicationServiceInterfaceMock_SetEntityService_Call) Run(run func(es entity.EntityServiceInterface)) *ApplicationServiceInterfaceMock_SetEntityService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entity.EntityServiceInterface
		if args[0] != nil {
			arg0 = args[0].(entity.EntityServiceInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_SetEntityService_Call) Return() *ApplicationServiceInterfaceMock_SetEntityService_Call {
	_c.Call.Return()
	return _c
}

func (_c *ApplicationServiceInterfaceMock_SetEntityService_Call) RunAndReturn(run func(es entity.EntityServiceInterface)) *ApplicationServiceInterfaceMock_SetEntityService_Call {
	_c.Run(run)
	return _c
}

// SetResourceService provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) SetResourceService(rs resource.ResourceServiceInterface) {
	_mock.Called(rs)
	return
}

// ApplicationServiceInterfaceMock_SetResourceService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetResourceService'
type ApplicationServiceInterfaceMock_SetResourceService_Call struct {
	*mock.Call
}

// SetResourceService is a helper method to define mock.On call
//   - rs resource.ResourceServiceInterface
func (_e *ApplicationServiceInterfaceMock_Expecter) SetResourceService(rs interface{}) *ApplicationServiceInterfaceMock_SetResourceService_Call {
	return &ApplicationServiceInterfaceMock_SetResourceService_Call{Call: _e.mock.On("SetResourceService", rs)}
}

func (_c *ApplicationServiceInterfaceMock_SetResourceService_Call) Run(run func(rs resource.ResourceServiceInterface)) *ApplicationServiceInterfaceMock_SetResourceService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 resource.ResourceServiceInterface
		if args[0] != nil {
			arg0 = args[0].(resource.ResourceServiceInterface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_SetResourceService_Call) Return() *ApplicationServiceInterfaceMock_SetResourceService_Call {
	_c.Call.Return()
	return _c
}

func (_c *ApplicationServiceInterfaceMock_SetResourceService_Call) RunAndReturn(run func(rs resource.ResourceServiceInterface)) *ApplicationServiceInterfaceMock_SetResourceService_Call {
	_c.Run(run)
	return _c
}

// UpdateApplication provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) UpdateApplication(ctx context.Context, appID string, app *model.ApplicationDTO) (*model.ApplicationDTO, *common.ServiceError) {
	ret := _mock.Called(ctx, appID, app)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApplication")
	}

	var r0 *model.ApplicationDTO
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ApplicationDTO) (*model.ApplicationDTO, *common.ServiceError)); ok {
		return returnFunc(ctx, appID, app)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ApplicationDTO) *model.ApplicationDTO); ok {
		r0 = returnFunc(ctx, appID, app)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApplicationDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.ApplicationDTO) *common.ServiceError); ok {
		r1 = returnFunc(ctx, appID, app)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_UpdateApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApplication'
type ApplicationServiceInterfaceMock_UpdateApplication_Call struct {
	*mock.Call
}

// UpdateApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - app *model.ApplicationDTO
func (_e *ApplicationServiceInterfaceMock_Expecter) UpdateApplication(ctx interface{}, appID interface{}, app interface{}) *ApplicationServiceInterfaceMock_UpdateApplication_Call {
	return &ApplicationServiceInterfaceMock_UpdateApplication_Call{Call: _e.mock.On("UpdateApplication", ctx, appID, app)}
}

func (_c *ApplicationServiceInterfaceMock_UpdateApplication_Call) Run(run func(ctx context.Context, appID string, app *model.ApplicationDTO)) *ApplicationServiceInterfaceMock_UpdateApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.ApplicationDTO
		if args[2] != nil {
			arg2 = args[2].(*model.ApplicationDTO)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_UpdateApplication_Call) Return(applicationDTO *model.ApplicationDTO, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_UpdateApplication_Call {
	_c.Call.Return(applicationDTO, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_UpdateApplication_Call) RunAndReturn(run func(ctx context.Context, appID string, app *model.ApplicationDTO) (*model.ApplicationDTO, *common.ServiceError)) *ApplicationServiceInterfaceMock_UpdateApplication_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApplicationInboundAccess provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) UpdateApplicationInboundAccess(ctx context.Context, appID string, identifier string) (*model.ApplicationInboundAccessResponse, *common.ServiceError) {
	ret := _mock.Called(ctx, appID, identifier)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApplicationInboundAccess")
	}

	var r0 *model.ApplicationInboundAccessResponse
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.ApplicationInboundAccessResponse, *common.ServiceError)); ok {
		return returnFunc(ctx, appID, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.ApplicationInboundAccessResponse); ok {
		r0 = returnFunc(ctx, appID, identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApplicationInboundAccessResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, appID, identifier)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApplicationInboundAccess'
type ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call struct {
	*mock.Call
}

// UpdateApplicationInboundAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - appID string
//   - identifier string
func (_e *ApplicationServiceInterfaceMock_Expecter) UpdateApplicationInboundAccess(ctx interface{}, appID interface{}, identifier interface{}) *ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call {
	return &ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call{Call: _e.mock.On("UpdateApplicationInboundAccess", ctx, appID, identifier)}
}

func (_c *ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call) Run(run func(ctx context.Context, appID string, identifier string)) *ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call) Return(applicationInboundAccessResponse *model.ApplicationInboundAccessResponse, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call {
	_c.Call.Return(applicationInboundAccessResponse, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call) RunAndReturn(run func(ctx context.Context, appID string, identifier string) (*model.ApplicationInboundAccessResponse, *common.ServiceError)) *ApplicationServiceInterfaceMock_UpdateApplicationInboundAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateApplication provides a mock function for the type ApplicationServiceInterfaceMock
func (_mock *ApplicationServiceInterfaceMock) ValidateApplication(ctx context.Context, app *model.ApplicationDTO) (*model.ApplicationProcessedDTO, *providers.InboundAuthConfigWithSecret, *common.ServiceError) {
	ret := _mock.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for ValidateApplication")
	}

	var r0 *model.ApplicationProcessedDTO
	var r1 *providers.InboundAuthConfigWithSecret
	var r2 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ApplicationDTO) (*model.ApplicationProcessedDTO, *providers.InboundAuthConfigWithSecret, *common.ServiceError)); ok {
		return returnFunc(ctx, app)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ApplicationDTO) *model.ApplicationProcessedDTO); ok {
		r0 = returnFunc(ctx, app)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ApplicationProcessedDTO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ApplicationDTO) *providers.InboundAuthConfigWithSecret); ok {
		r1 = returnFunc(ctx, app)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*providers.InboundAuthConfigWithSecret)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *model.ApplicationDTO) *common.ServiceError); ok {
		r2 = returnFunc(ctx, app)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*common.ServiceError)
		}
	}
	return r0, r1, r2
}

// ApplicationServiceInterfaceMock_ValidateApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateApplication'
type ApplicationServiceInterfaceMock_ValidateApplication_Call struct {
	*mock.Call
}

// ValidateApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - app *model.ApplicationDTO
func (_e *ApplicationServiceInterfaceMock_Expecter) ValidateApplication(ctx interface{}, app interface{}) *ApplicationServiceInterfaceMock_ValidateApplication_Call {
	return &ApplicationServiceInterfaceMock_ValidateApplication_Call{Call: _e.mock.On("ValidateApplication", ctx, app)}
}

func (_c *ApplicationServiceInterfaceMock_ValidateApplication_Call) Run(run func(ctx context.Context, app *model.ApplicationDTO)) *ApplicationServiceInterfaceMock_ValidateApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ApplicationDTO
		if args[1] != nil {
			arg1 = args[1].(*model.ApplicationDTO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ApplicationServiceInterfaceMock_ValidateApplication_Call) Return(applicationProcessedDTO *model.ApplicationProcessedDTO, inboundAuthConfigWithSecret *providers.InboundAuthConfigWithSecret, serviceError *common.ServiceError) *ApplicationServiceInterfaceMock_ValidateApplication_Call {
	_c.Call.Return(applicationProcessedDTO, inboundAuthConfigWithSecret, serviceError)
	return _c
}

func (_c *ApplicationServiceInterfaceMock_ValidateApplication_Call) RunAndReturn(run func(ctx context.Context, app *model.ApplicationDTO) (*model.ApplicationProcessedDTO, *providers.InboundAuthConfigWithSecret, *common.ServiceError)) *ApplicationServiceInterfaceMock_ValidateApplication_Call {
	_c.Call.Return(run)
	return _c
}
