// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resource

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewEntityOwnerLookupMock creates a new instance of EntityOwnerLookupMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntityOwnerLookupMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntityOwnerLookupMock {
	mock := &EntityOwnerLookupMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EntityOwnerLookupMock is an autogenerated mock type for the EntityOwnerLookup type
type EntityOwnerLookupMock struct {
	mock.Mock
}

type EntityOwnerLookupMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EntityOwnerLookupMock) EXPECT() *EntityOwnerLookupMock_Expecter {
	return &EntityOwnerLookupMock_Expecter{mock: &_m.Mock}
}

// GetResourceServerOwner provides a mock function for the type EntityOwnerLookupMock
func (_mock *EntityOwnerLookupMock) GetResourceServerOwner(ctx context.Context, resourceServerID string) (*ResourceServerOwner, error) {
	ret := _mock.Called(ctx, resourceServerID)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceServerOwner")
	}

	var r0 *ResourceServerOwner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ResourceServerOwner, error)); ok {
		return returnFunc(ctx, resourceServerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ResourceServerOwner); ok {
		r0 = returnFunc(ctx, resourceServerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ResourceServerOwner)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, resourceServerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EntityOwnerLookupMock_GetResourceServerOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceServerOwner'
type EntityOwnerLookupMock_GetResourceServerOwner_Call struct {
	*mock.Call
}

// GetResourceServerOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceServerID string
func (_e *EntityOwnerLookupMock_Expecter) GetResourceServerOwner(ctx interface{}, resourceServerID interface{}) *EntityOwnerLookupMock_GetResourceServerOwner_Call {
	return &EntityOwnerLookupMock_GetResourceServerOwner_Call{Call: _e.mock.On("GetResourceServerOwner", ctx, resourceServerID)}
}

func (_c *EntityOwnerLookupMock_GetResourceServerOwner_Call) Run(run func(ctx context.Context, resourceServerID string)) *EntityOwnerLookupMock_GetResourceServerOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityOwnerLookupMock_GetResourceServerOwner_Call) Return(resourceServerOwner *ResourceServerOwner, err error) *EntityOwnerLookupMock_GetResourceServerOwner_Call {
	_c.Call.Return(resourceServerOwner, err)
	return _c
}

func (_c *EntityOwnerLookupMock_GetResourceServerOwner_Call) RunAndReturn(run func(ctx context.Context, resourceServerID string) (*ResourceServerOwner, error)) *EntityOwnerLookupMock_GetResourceServerOwner_Call {
	_c.Call.Return(run)
	return _c
}
