// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authz

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewAuthorizationCodeStoreInterfaceMock creates a new instance of AuthorizationCodeStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationCodeStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationCodeStoreInterfaceMock {
	mock := &AuthorizationCodeStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthorizationCodeStoreInterfaceMock is an autogenerated mock type for the AuthorizationCodeStoreInterface type
type AuthorizationCodeStoreInterfaceMock struct {
	mock.Mock
}

type AuthorizationCodeStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizationCodeStoreInterfaceMock) EXPECT() *AuthorizationCodeStoreInterfaceMock_Expecter {
	return &AuthorizationCodeStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// ConsumeAuthorizationCode provides a mock function for the type AuthorizationCodeStoreInterfaceMock
func (_mock *AuthorizationCodeStoreInterfaceMock) ConsumeAuthorizationCode(ctx context.Context, authCode string) (bool, error) {
	ret := _mock.Called(ctx, authCode)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeAuthorizationCode")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, authCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, authCode)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, authCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeAuthorizationCode'
type AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call struct {
	*mock.Call
}

// ConsumeAuthorizationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - authCode string
func (_e *AuthorizationCodeStoreInterfaceMock_Expecter) ConsumeAuthorizationCode(ctx interface{}, authCode interface{}) *AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call {
	return &AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call{Call: _e.mock.On("ConsumeAuthorizationCode", ctx, authCode)}
}

func (_c *AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call) Run(run func(ctx context.Context, authCode string)) *AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call) Return(b bool, err error) *AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call) RunAndReturn(run func(ctx context.Context, authCode string) (bool, error)) *AuthorizationCodeStoreInterfaceMock_ConsumeAuthorizationCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorizationCode provides a mock function for the type AuthorizationCodeStoreInterfaceMock
func (_mock *AuthorizationCodeStoreInterfaceMock) GetAuthorizationCode(ctx context.Context, authCode string) (*AuthorizationCode, error) {
	ret := _mock.Called(ctx, authCode)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationCode")
	}

	var r0 *AuthorizationCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*AuthorizationCode, error)); ok {
		return returnFunc(ctx, authCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *AuthorizationCode); ok {
		r0 = returnFunc(ctx, authCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthorizationCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, authCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizationCode'
type AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call struct {
	*mock.Call
}

// GetAuthorizationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - authCode string
func (_e *AuthorizationCodeStoreInterfaceMock_Expecter) GetAuthorizationCode(ctx interface{}, authCode interface{}) *AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call {
	return &AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call{Call: _e.mock.On("GetAuthorizationCode", ctx, authCode)}
}

func (_c *AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call) Run(run func(ctx context.Context, authCode string)) *AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call) Return(authorizationCode *AuthorizationCode, err error) *AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call {
	_c.Call.Return(authorizationCode, err)
	return _c
}

func (_c *AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call) RunAndReturn(run func(ctx context.Context, authCode string) (*AuthorizationCode, error)) *AuthorizationCodeStoreInterfaceMock_GetAuthorizationCode_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAuthorizationCode provides a mock function for the type AuthorizationCodeStoreInterfaceMock
func (_mock *AuthorizationCodeStoreInterfaceMock) InsertAuthorizationCode(ctx context.Context, authzCode AuthorizationCode) error {
	ret := _mock.Called(ctx, authzCode)

	if len(ret) == 0 {
		panic("no return value specified for InsertAuthorizationCode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AuthorizationCode) error); ok {
		r0 = returnFunc(ctx, authzCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAuthorizationCode'
type AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call struct {
	*mock.Call
}

// InsertAuthorizationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - authzCode AuthorizationCode
func (_e *AuthorizationCodeStoreInterfaceMock_Expecter) InsertAuthorizationCode(ctx interface{}, authzCode interface{}) *AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call {
	return &AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call{Call: _e.mock.On("InsertAuthorizationCode", ctx, authzCode)}
}

func (_c *AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call) Run(run func(ctx context.Context, authzCode AuthorizationCode)) *AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AuthorizationCode
		if args[1] != nil {
			arg1 = args[1].(AuthorizationCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call) Return(err error) *AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call) RunAndReturn(run func(ctx context.Context, authzCode AuthorizationCode) error) *AuthorizationCodeStoreInterfaceMock_InsertAuthorizationCode_Call {
	_c.Call.Return(run)
	return _c
}
