// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authz

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// newAuthCodeRedisClientMock creates a new instance of authCodeRedisClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newAuthCodeRedisClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *authCodeRedisClientMock {
	mock := &authCodeRedisClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// authCodeRedisClientMock is an autogenerated mock type for the authCodeRedisClient type
type authCodeRedisClientMock struct {
	mock.Mock
}

type authCodeRedisClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *authCodeRedisClientMock) EXPECT() *authCodeRedisClientMock_Expecter {
	return &authCodeRedisClientMock_Expecter{mock: &_m.Mock}
}

// Eval provides a mock function for the type authCodeRedisClientMock
func (_mock *authCodeRedisClientMock) Eval(ctx context.Context, script string, keys []string, args ...interface{}) *redis.Cmd {
	var _ca []interface{}
	_ca = append(_ca, ctx, script, keys)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Eval")
	}

	var r0 *redis.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, ...interface{}) *redis.Cmd); ok {
		r0 = returnFunc(ctx, script, keys, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Cmd)
		}
	}
	return r0
}

// authCodeRedisClientMock_Eval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eval'
type authCodeRedisClientMock_Eval_Call struct {
	*mock.Call
}

// Eval is a helper method to define mock.On call
//   - ctx context.Context
//   - script string
//   - keys []string
//   - args ...interface{}
func (_e *authCodeRedisClientMock_Expecter) Eval(ctx interface{}, script interface{}, keys interface{}, args ...interface{}) *authCodeRedisClientMock_Eval_Call {
	return &authCodeRedisClientMock_Eval_Call{Call: _e.mock.On("Eval",
		append([]interface{}{ctx, script, keys}, args...)...)}
}

func (_c *authCodeRedisClientMock_Eval_Call) Run(run func(ctx context.Context, script string, keys []string, args ...interface{})) *authCodeRedisClientMock_Eval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []interface{}
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *authCodeRedisClientMock_Eval_Call) Return(cmd *redis.Cmd) *authCodeRedisClientMock_Eval_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *authCodeRedisClientMock_Eval_Call) RunAndReturn(run func(ctx context.Context, script string, keys []string, args ...interface{}) *redis.Cmd) *authCodeRedisClientMock_Eval_Call {
	_c.Call.Return(run)
	return _c
}

// EvalRO provides a mock function for the type authCodeRedisClientMock
func (_mock *authCodeRedisClientMock) EvalRO(ctx context.Context, script string, keys []string, args ...interface{}) *redis.Cmd {
	var _ca []interface{}
	_ca = append(_ca, ctx, script, keys)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EvalRO")
	}

	var r0 *redis.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, ...interface{}) *redis.Cmd); ok {
		r0 = returnFunc(ctx, script, keys, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Cmd)
		}
	}
	return r0
}

// authCodeRedisClientMock_EvalRO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalRO'
type authCodeRedisClientMock_EvalRO_Call struct {
	*mock.Call
}

// EvalRO is a helper method to define mock.On call
//   - ctx context.Context
//   - script string
//   - keys []string
//   - args ...interface{}
func (_e *authCodeRedisClientMock_Expecter) EvalRO(ctx interface{}, script interface{}, keys interface{}, args ...interface{}) *authCodeRedisClientMock_EvalRO_Call {
	return &authCodeRedisClientMock_EvalRO_Call{Call: _e.mock.On("EvalRO",
		append([]interface{}{ctx, script, keys}, args...)...)}
}

func (_c *authCodeRedisClientMock_EvalRO_Call) Run(run func(ctx context.Context, script string, keys []string, args ...interface{})) *authCodeRedisClientMock_EvalRO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []interface{}
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *authCodeRedisClientMock_EvalRO_Call) Return(cmd *redis.Cmd) *authCodeRedisClientMock_EvalRO_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *authCodeRedisClientMock_EvalRO_Call) RunAndReturn(run func(ctx context.Context, script string, keys []string, args ...interface{}) *redis.Cmd) *authCodeRedisClientMock_EvalRO_Call {
	_c.Call.Return(run)
	return _c
}

// EvalSha provides a mock function for the type authCodeRedisClientMock
func (_mock *authCodeRedisClientMock) EvalSha(ctx context.Context, sha1 string, keys []string, args ...interface{}) *redis.Cmd {
	var _ca []interface{}
	_ca = append(_ca, ctx, sha1, keys)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EvalSha")
	}

	var r0 *redis.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, ...interface{}) *redis.Cmd); ok {
		r0 = returnFunc(ctx, sha1, keys, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Cmd)
		}
	}
	return r0
}

// authCodeRedisClientMock_EvalSha_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalSha'
type authCodeRedisClientMock_EvalSha_Call struct {
	*mock.Call
}

// EvalSha is a helper method to define mock.On call
//   - ctx context.Context
//   - sha1 string
//   - keys []string
//   - args ...interface{}
func (_e *authCodeRedisClientMock_Expecter) EvalSha(ctx interface{}, sha1 interface{}, keys interface{}, args ...interface{}) *authCodeRedisClientMock_EvalSha_Call {
	return &authCodeRedisClientMock_EvalSha_Call{Call: _e.mock.On("EvalSha",
		append([]interface{}{ctx, sha1, keys}, args...)...)}
}

func (_c *authCodeRedisClientMock_EvalSha_Call) Run(run func(ctx context.Context, sha1 string, keys []string, args ...interface{})) *authCodeRedisClientMock_EvalSha_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []interface{}
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *authCodeRedisClientMock_EvalSha_Call) Return(cmd *redis.Cmd) *authCodeRedisClientMock_EvalSha_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *authCodeRedisClientMock_EvalSha_Call) RunAndReturn(run func(ctx context.Context, sha1 string, keys []string, args ...interface{}) *redis.Cmd) *authCodeRedisClientMock_EvalSha_Call {
	_c.Call.Return(run)
	return _c
}

// EvalShaRO provides a mock function for the type authCodeRedisClientMock
func (_mock *authCodeRedisClientMock) EvalShaRO(ctx context.Context, sha1 string, keys []string, args ...interface{}) *redis.Cmd {
	var _ca []interface{}
	_ca = append(_ca, ctx, sha1, keys)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EvalShaRO")
	}

	var r0 *redis.Cmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, ...interface{}) *redis.Cmd); ok {
		r0 = returnFunc(ctx, sha1, keys, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Cmd)
		}
	}
	return r0
}

// authCodeRedisClientMock_EvalShaRO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalShaRO'
type authCodeRedisClientMock_EvalShaRO_Call struct {
	*mock.Call
}

// EvalShaRO is a helper method to define mock.On call
//   - ctx context.Context
//   - sha1 string
//   - keys []string
//   - args ...interface{}
func (_e *authCodeRedisClientMock_Expecter) EvalShaRO(ctx interface{}, sha1 interface{}, keys interface{}, args ...interface{}) *authCodeRedisClientMock_EvalShaRO_Call {
	return &authCodeRedisClientMock_EvalShaRO_Call{Call: _e.mock.On("EvalShaRO",
		append([]interface{}{ctx, sha1, keys}, args...)...)}
}

func (_c *authCodeRedisClientMock_EvalShaRO_Call) Run(run func(ctx context.Context, sha1 string, keys []string, args ...interface{})) *authCodeRedisClientMock_EvalShaRO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []interface{}
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *authCodeRedisClientMock_EvalShaRO_Call) Return(cmd *redis.Cmd) *authCodeRedisClientMock_EvalShaRO_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *authCodeRedisClientMock_EvalShaRO_Call) RunAndReturn(run func(ctx context.Context, sha1 string, keys []string, args ...interface{}) *redis.Cmd) *authCodeRedisClientMock_EvalShaRO_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type authCodeRedisClientMock
func (_mock *authCodeRedisClientMock) Get(ctx context.Context, key string) *redis.StringCmd {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *redis.StringCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *redis.StringCmd); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StringCmd)
		}
	}
	return r0
}

// authCodeRedisClientMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type authCodeRedisClientMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *authCodeRedisClientMock_Expecter) Get(ctx interface{}, key interface{}) *authCodeRedisClientMock_Get_Call {
	return &authCodeRedisClientMock_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *authCodeRedisClientMock_Get_Call) Run(run func(ctx context.Context, key string)) *authCodeRedisClientMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *authCodeRedisClientMock_Get_Call) Return(stringCmd *redis.StringCmd) *authCodeRedisClientMock_Get_Call {
	_c.Call.Return(stringCmd)
	return _c
}

func (_c *authCodeRedisClientMock_Get_Call) RunAndReturn(run func(ctx context.Context, key string) *redis.StringCmd) *authCodeRedisClientMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ScriptExists provides a mock function for the type authCodeRedisClientMock
func (_mock *authCodeRedisClientMock) ScriptExists(ctx context.Context, hashes ...string) *redis.BoolSliceCmd {
	// string
	_va := make([]interface{}, len(hashes))
	for _i := range hashes {
		_va[_i] = hashes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ScriptExists")
	}

	var r0 *redis.BoolSliceCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) *redis.BoolSliceCmd); ok {
		r0 = returnFunc(ctx, hashes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.BoolSliceCmd)
		}
	}
	return r0
}

// authCodeRedisClientMock_ScriptExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScriptExists'
type authCodeRedisClientMock_ScriptExists_Call struct {
	*mock.Call
}

// ScriptExists is a helper method to define mock.On call
//   - ctx context.Context
//   - hashes ...string
func (_e *authCodeRedisClientMock_Expecter) ScriptExists(ctx interface{}, hashes ...interface{}) *authCodeRedisClientMock_ScriptExists_Call {
	return &authCodeRedisClientMock_ScriptExists_Call{Call: _e.mock.On("ScriptExists",
		append([]interface{}{ctx}, hashes...)...)}
}

func (_c *authCodeRedisClientMock_ScriptExists_Call) Run(run func(ctx context.Context, hashes ...string)) *authCodeRedisClientMock_ScriptExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *authCodeRedisClientMock_ScriptExists_Call) Return(boolSliceCmd *redis.BoolSliceCmd) *authCodeRedisClientMock_ScriptExists_Call {
	_c.Call.Return(boolSliceCmd)
	return _c
}

func (_c *authCodeRedisClientMock_ScriptExists_Call) RunAndReturn(run func(ctx context.Context, hashes ...string) *redis.BoolSliceCmd) *authCodeRedisClientMock_ScriptExists_Call {
	_c.Call.Return(run)
	return _c
}

// ScriptLoad provides a mock function for the type authCodeRedisClientMock
func (_mock *authCodeRedisClientMock) ScriptLoad(ctx context.Context, script string) *redis.StringCmd {
	ret := _mock.Called(ctx, script)

	if len(ret) == 0 {
		panic("no return value specified for ScriptLoad")
	}

	var r0 *redis.StringCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *redis.StringCmd); ok {
		r0 = returnFunc(ctx, script)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StringCmd)
		}
	}
	return r0
}

// authCodeRedisClientMock_ScriptLoad_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScriptLoad'
type authCodeRedisClientMock_ScriptLoad_Call struct {
	*mock.Call
}

// ScriptLoad is a helper method to define mock.On call
//   - ctx context.Context
//   - script string
func (_e *authCodeRedisClientMock_Expecter) ScriptLoad(ctx interface{}, script interface{}) *authCodeRedisClientMock_ScriptLoad_Call {
	return &authCodeRedisClientMock_ScriptLoad_Call{Call: _e.mock.On("ScriptLoad", ctx, script)}
}

func (_c *authCodeRedisClientMock_ScriptLoad_Call) Run(run func(ctx context.Context, script string)) *authCodeRedisClientMock_ScriptLoad_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *authCodeRedisClientMock_ScriptLoad_Call) Return(stringCmd *redis.StringCmd) *authCodeRedisClientMock_ScriptLoad_Call {
	_c.Call.Return(stringCmd)
	return _c
}

func (_c *authCodeRedisClientMock_ScriptLoad_Call) RunAndReturn(run func(ctx context.Context, script string) *redis.StringCmd) *authCodeRedisClientMock_ScriptLoad_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type authCodeRedisClientMock
func (_mock *authCodeRedisClientMock) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) *redis.StatusCmd {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *redis.StatusCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) *redis.StatusCmd); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}
	return r0
}

// authCodeRedisClientMock_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type authCodeRedisClientMock_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *authCodeRedisClientMock_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *authCodeRedisClientMock_Set_Call {
	return &authCodeRedisClientMock_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *authCodeRedisClientMock_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *authCodeRedisClientMock_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *authCodeRedisClientMock_Set_Call) Return(statusCmd *redis.StatusCmd) *authCodeRedisClientMock_Set_Call {
	_c.Call.Return(statusCmd)
	return _c
}

func (_c *authCodeRedisClientMock_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value interface{}, expiration time.Duration) *redis.StatusCmd) *authCodeRedisClientMock_Set_Call {
	_c.Call.Return(run)
	return _c
}
