// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package par

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// newParRedisClientMock creates a new instance of parRedisClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newParRedisClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *parRedisClientMock {
	mock := &parRedisClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// parRedisClientMock is an autogenerated mock type for the parRedisClient type
type parRedisClientMock struct {
	mock.Mock
}

type parRedisClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *parRedisClientMock) EXPECT() *parRedisClientMock_Expecter {
	return &parRedisClientMock_Expecter{mock: &_m.Mock}
}

// GetDel provides a mock function for the type parRedisClientMock
func (_mock *parRedisClientMock) GetDel(ctx context.Context, key string) *redis.StringCmd {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetDel")
	}

	var r0 *redis.StringCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *redis.StringCmd); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StringCmd)
		}
	}
	return r0
}

// parRedisClientMock_GetDel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDel'
type parRedisClientMock_GetDel_Call struct {
	*mock.Call
}

// GetDel is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *parRedisClientMock_Expecter) GetDel(ctx interface{}, key interface{}) *parRedisClientMock_GetDel_Call {
	return &parRedisClientMock_GetDel_Call{Call: _e.mock.On("GetDel", ctx, key)}
}

func (_c *parRedisClientMock_GetDel_Call) Run(run func(ctx context.Context, key string)) *parRedisClientMock_GetDel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *parRedisClientMock_GetDel_Call) Return(stringCmd *redis.StringCmd) *parRedisClientMock_GetDel_Call {
	_c.Call.Return(stringCmd)
	return _c
}

func (_c *parRedisClientMock_GetDel_Call) RunAndReturn(run func(ctx context.Context, key string) *redis.StringCmd) *parRedisClientMock_GetDel_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type parRedisClientMock
func (_mock *parRedisClientMock) Set(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *redis.StatusCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) *redis.StatusCmd); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}
	return r0
}

// parRedisClientMock_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type parRedisClientMock_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *parRedisClientMock_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *parRedisClientMock_Set_Call {
	return &parRedisClientMock_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *parRedisClientMock_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *parRedisClientMock_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *parRedisClientMock_Set_Call) Return(statusCmd *redis.StatusCmd) *parRedisClientMock_Set_Call {
	_c.Call.Return(statusCmd)
	return _c
}

func (_c *parRedisClientMock_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd) *parRedisClientMock_Set_Call {
	_c.Call.Return(run)
	return _c
}
